### ISSUE TITLE
 Implement List blocks (collection and item)

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#106]
Acceptance criteria:

- [x] A list of collections or items is displayed 
- [x] The list is paginated
- [x] Truncated pagination controls appear in the header of the list
- [x] Options drop-down menu appears in the header of the list. Options include:
       - List sort
       - Go to list page
       - number of list items per page
- [ ] List/grid view (possibly not MVP)
- [x] A scoped search input appears in the header of the list
- [ ] Entering search terms in the input and clicking the search icon takes a user to the search results page
- [x] Each list item contains an image and title/description (list item might not have a description)
   - [ ] Each list item only display fields in English. unless english field isnot available, then use the available language
   - [x] For collection, fields to display are: Title, first 2 sentences of description with ellipsis 
   - [ ] For item, fields to display are: Author/creator, Date created, Date publish  
- [x] Clicking a collection (or an item) takes a user to the appropriate detail view

This task should first be explored as a generalizable feature that can be applied to both collection list and item list views. If there are difficulties with generalizing the feature then individualized lists can be developed.

There will also need to be a flag on an item that marks it as the preview image to be displayed for the collection. If there is no image available for the collection a default placeholder icon should be displayed. For items, the placeholder image should capture the media type (e.g. audio files might have an icon of a speaker).

**Comment by jabrah** [comment]
Will likely implement this as a custom JS component and represent the list of items as a Search Result. This will be a large and complicated component, so we will likely work simultaneously on different aspects.

**Mockups**: https://www.sketch.com/s/08f8c43e-b7f5-4607-a176-158b42c0f8a6/a/R0dy2Q

### Tasks

* Component skeleton with barebones layout and placeholder elements (2d)
* Get basic search functionality, must send a search request and hook in search results ~~(3d - assuming search results already works, see #111 )~~
  * Create search results UI (Reqs in #111). This is basically just the "list view" of the results
    * Results templating, css (2d)
    * Refresh the list in response to new searches (1d)
* Add paging (3d)
* Add search options (sort by, # results per page, etc) (2d)
* ~~Add facets (3d - on top of #110)~~
* Make sure component is responsive (?d)
* testing (5d)

**Comment by htpvu** [comment]
removing the task from adding facet from this ticket. to be done in https://github.com/jhu-idc/iDC-general/issues/105
