### ISSUE TITLE
Implement item detail

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#109]
Acceptance criteria:
- [x] Optionally display the about the item description if one exists (addressed by https://github.com/jhu-idc/idc-isle-dc/pull/135)
- [x] Display an oversized image of the item if it exists (addressed by jhu-idc/idc-isle-dc#135)
- [x] But if an image has the “hi-res” tag, then display its low-res derivative instead, and provide a link to download the hi-res image. (see https://github.com/jhu-idc/iDC-general/issues/315)
- [x] Unless hi-res image also have a restricted access tag, then provide link to send email to request the image (see https://github.com/jhu-idc/iDC-general/issues/305)
- [x] Display media player for item if it is relevant (addressed by https://github.com/jhu-idc/idc-isle-dc/pull/135)
Image viewer for images
Audio player for audio files
Video player for video files

- [x] List of all of the item's metadata: in order of Title, Description, Image, then the rest of the metadata (addressed by https://github.com/jhu-idc/idc-isle-dc/pull/135)
   - [x] display available language tags in visual tags (addressed by https://github.com/jhu-idc/idc-isle-dc/pull/135)
   - [x] display language tags in appropriate html tags to enable screenreader to process that tag. (addressed by https://github.com/jhu-idc/idc-isle-dc/pull/135)
- [x] List item’s URI (aka its Citable URI) along with its metadata. (iDC-19) (addressed by https://github.com/jhu-idc/idc-isle-dc/pull/135)

Button group that when clicked:
- [x] Allows download of the item media via a link (see https://github.com/jhu-idc/iDC-general/issues/315)
- [x] If item’s image is marked as restricted access, provide link to send email request the image (iDC-15) (see https://github.com/jhu-idc/iDC-general/issues/305)
~~- [ ] Allows download of the whole digital object~~ this is captured by download media of the item and metadata export, so striking this requirement unless we determine otherwise
- [ ] Exports item metadata (see https://github.com/jhu-idc/iDC-general/issues/108)
- [ ] Opens a modal for displaying 3 styles of citation string for the item (see https://github.com/jhu-idc/iDC-general/issues/119)
- [x] Opens a modal with a form to ask questions about an item (see https://github.com/jhu-idc/iDC-general/issues/107)

**Comment by jabrah** [comment]
* Will have to do some investigation to see if Drupal has a way to display AV data
* If the node has a link to a binary package to download or if there is a download service, then allowing download should be easy
* Export metadata handled in a separate ticket
* Are these included in the node data or will they need to be generated? If so generated by a service or generated directly in the UI?
* Contact form for an item should be a separate ticket

**Comment by jaredgalanis** [comment]
export metadata modal #108 and contact form #103 are prerequisites

- [x] templating and css (2d)
- [x] integrate media players (5d)
- [ ] hi rez image permissions (3d)
- [ ] integration with citation service (1d)
- [x] integrate with service to download full item (1d)
- [ ] export metadata (see #108)
- [x] contact form modal (see #103)
- [ ] ~~implement cropping / downloading of images (2w)~~ we've discussed striking this requirement due to the complexity involved balanced against the limited value of the use case. it is unclear that the cropping functionality proposed would actually store a new copy of the cropped image for later use, but that would be a relatively complex engineering task if so. a user could easily crop an image locally on their computer and upload a new copy of the media if such functionality is needed. arguably, this is not something that would happen in the typical flow of a user's use of the system. needs stakeholder input.

**Comment by htpvu** [comment]
@jabrah the work to create the contact form does have a separate this ticket. but this ticket should  cover putting in a link to invoke that form. right?

**Comment by jabrah** [comment]
This contact form and the other contact form in #103 have different requirements. I was thinking that they'd be done separately

**Comment by jabrah** [comment]
To clarify the contact requirement: #103 will form the base of the contact component, but this ticket will require more work to augment the component's functionality, accounted for in #107

**Comment by htpvu** [comment]
There are specific requirements relating to how links to Archive Space and Horizon has to be rendered, as well as  requirements for dynamically generated text field for archive space.

Please consult this use case for specific requirements https://docs.google.com/document/d/18f-YltABoqf0MVCfChj_u-VrRcR0V8Gz/edit. also please ping me if the usecase does n't make enough sense.

**Comment by htpvu** [comment]
notes for implementing hi-res image requirements:
- flag for indicating whether a hires image is restricted is not yet implemented, but will be implemnted by @bseeger  - https://github.com/jhu-idc/iDC-general/issues/305
- if an image is restricted, clicking on its hi-res/download link open a email modal to let users email collection admin for access
- if an image is not restricted, download image onto users computer ( TODO: verify with Bethany or Aaron)

**Comment by jabrah** [comment]
We've addressed much of this ticket in PR https://github.com/jhu-idc/idc-isle-dc/pull/135, leaving the following still to be done:

* Metadata export
* Citation export
* Item download
* High resolution image handling

These items require interfacing with custom services in various states of completion, so we've implemented what we could without relying on completed services. These TODOs should each have individual tickets already
