### ISSUE TITLE
Implement Search Results page

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#111]
Design: https://www.sketch.com/s/32c87472-3a88-4caf-bd91-aecaa9c4cbcb
Acceptance criteria:
- [x] For each item in the search result, display the following fields, in English, if they are available
   - [x] title
   - [x] Author Name
   - [x] Created Date
   - [x] Publication Date
- [x] Search results page contains all the list view sorting, pagination, faceting and search input functionality
- [ ] If facets or search terms are applied they will appear in filters applied block at the top of the page
- [ ] Clicking clear filters will remove all filters and display a default ordered list view of all collection items
- [x] Collection / item should be a filter that can be applied depending on whether a search is directed at collections or items
- [x] (moved to https://github.com/jhu-sheridan-libraries/iDC-general/issues/118)  Clicking “export search result’s metadata” will produce a CSV file of result’s metadata
    - [x] A modal popup allows users to select which metadata fields he/she wants to export for this result set. 
    - [x] Users are allowed to select between export the entire result set or export the current page of the result set
- [x] (moved to https://github.com/jhu-sheridan-libraries/iDC-general/issues/119)  Clicking “Download Bibliographic Information” will trigger process to generate citation for selected items and download resulting file to user’s computer

This page should be the results page for collection, item, global and advanced searches. As such it will need to include enough filter criteria to encapsulate those searches and produce relevant search result lists.

context doc: https://docs.google.com/document/d/1AYsB0TnCafhWOgpCfzQCsfBzhYgGwPcuJXxASg4GZVE/edit#heading=h.50aihgcgszpm

**Comment by jabrah** [comment]
* Investigate the shape of search results from Solr (assuming we hit Solr directly instead of routing through Drupal APIs)
  * This may influence the Solr config, depending on what data we need available in the results response. Ideally, we will have all the data we need to display each search result entry without having to make extra requests to the back end for extra node data
* Recommend: move "export metadata" to be moved to a different ticket. Same suggestion for "export result set/results page"

**Comment by htpvu** [comment]
@jabrah will move the export stuff to new tickets. do you have estimate for the ticket WITHOUT those two elements?

**Comment by jabrah** [comment]
Most functionality described above will be done while implementing Item List Blocks (#106). That ticket outlines a generalized search implementation at a high level. A specific "search results" page will be shown in response to a global search or advanced search, not associated with a specific collection or item.

Tasks:

* [x] Setup container page in Drupal (1d) https://github.com/jhu-sheridan-libraries/iDC-general/issues/120 
* [ ] Separate "filters" section at top of page, allowing users to de-select filters and re-run the search (2d) https://github.com/jhu-sheridan-libraries/iDC-general/issues/121
* [x] Figure out how to route a search to this page (5d) https://github.com/jhu-sheridan-libraries/iDC-general/issues/122
  * Just some Drupal related unknowns here, like will we just do something like routing the site to a static relative URL or something? 
- [ ] Test JS components (mostly the "filters" section described here) (1d)
