### ISSUE TITLE
Implement Advanced Search page

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#112]
Use case: https://docs.google.com/document/d/1U8bBc_Tl_dpVzZxa2DNXCsBpln-tI7pGg3RQwRxkV-g/edit#

Design: https://www.sketch.com/s/dd188010-34c7-44d6-9da0-cf495e4ae411

Acceptance criteria:
- [x] A user can add rows that represent either standard or proximity based search criteria
- [x] There is no conceptual limit to the number of rows that can be added
- [x] Proximity searches allows a user to search the proximity of terms within other terms specified
- [x] Standard searches allow for the search by terms targeting certain fields
- [x] A user can limit search results by collection, language, resource type and specify result sorting while building the search
- [x] A user is also instructed by tips for explaining how to use the advanced search feature

We might be able to break the advanced search into:
- Standard search
- Proximity search
- Search result limiter controls

Since Solr is the default search system for Isle/Islandora, this task will involve interfacing with Solr and the Drupal search API.

**Comment by jaredgalanis** [comment]
- [ ] templating and css (2d)
- [ ] implement integration with search api and other related mechanics (12d)

**Comment by jabrah** [comment]
## Tasks 

Below is a list of more specific work tasks to implement the features listed above. Proposed dates assume no days off.

* [x] Advanced search terms UI, first pass -- Basically make a first pass at what a single term looks like, with some other controls
* [x] Add arbitrary number of rows
* [x] Form validation
* [x] Query service: Generate query from UI
_**(Up to here, target 4/30)** : At this point, a user should be able to create advanced search terms and do a search_
* [x] Create an "autocomplete" component that can search for items using Drupal's JSONAPI
* [x] Filter: collection -- allow user to look up a collection and narrow the search query by the collection
* [x] Filter: language -- allow user to look up language (taxonomy) and apply it to the search query
* [x] Filter: resource type -- allow user to look up resource types (taxonomy), select and apply it to the search query
_**(Up to here, perhaps 5/7)** : At this point, a user should be able to the above, plus apply collection, language, resource type filters -- pretty much feature complete_
* [ ] General UI
  * [ ] Placement of advanced search UI -- Inside of the already existing search component acceptable?
        Current mockups have a stand-alone page dedicated to generating an advanced search query, disconnected from the results page. This doesn't really mesh well with our current search interface designs that display results along side the search interface
  * [ ] Advanced search UI layout, 2nd pass -- make sure the layout of advanced search specific components make sense and are minimally responsive
  * [ ] Minimum accessibility pass -- at a minimum, make sure there are no reported errors in your accessibility tool of choice
  * [ ] Polish of various components -- make sure component designs are consistent with the rest of the site.
        For example, dropdowns, buttons, etc should look and feel like counterparts in other parts of the site
_**(Up to here, hopefully 5/14)**_
* [ ] _Initialize rows from a URL query param -- nice to have_
      Note about this task: strictly speaking, this is not in the use case. However it does effect user experience, mostly when using the browser forward/back buttons. It would also enable easier sharing of advanced search results apart from the metadata exporting

**Comment by jabrah** [comment]
### Questions

* Should we merge the "search [results]" and "advanced search" pages?
* Should we enable advanced search UI in other search interfaces?

**Comment by jabrah** [comment]
Currently, resource type only appears on Repository Items, and `collection` is not selectable anywhere. Arguably, then, the resource type filter is already handled by facets

**Comment by jabrah** [comment]
Related: https://github.com/jhu-idc/iDC-general/issues/341
Not sure if this issue should be considered a blocker. The search query generation in the current UI works up until the query hits the character limit
