### ISSUE TITLE
Enable S3 in the k8s stacks

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#342]
S3 is required for all `drupal-static` images published after `ghcr.io/jhu-sheridan-libraries/idc-isle-dc/drupal-static:a5decfb`  (TODO:  create ticket for tagging idc-isle-dc, so that image tags make sense as in terms of the concept 'after'.  It's impossible to tell by visual inspection of the git hash alone).

Configure all cloud instances to use S3.  This entails, for each cloud environment,
* Creating an S3 bucket for content, and setting appropriate permissions on it
* [Configuring Drupal](https://github.com/jhu-idc/idc-isle-dc#s3-file-storage) for the credentials and identity of the bucket
* Manually verifying (or getting somebody to verify) that Drupal can successfully store content in its configured S3 environment

The local k8s environment would need to have minio added to its stack, in order to provide an S3 endpoint to use locally. 

This is an umbrella ticket encompassing:
- [x] [Set up the test environment for S3](https://github.com/jhu-idc/idcApp-k8s/issues/45)
- [x] [Set up the stage environment for S3](https://github.com/jhu-idc/idcApp-k8s/issues/46)
- [x] If it's not to early to do so, set up the production environment for S3
- [ ] [Add minio and set up the local environment for S3](https://github.com/jhu-idc/idcApp-k8s/issues/47)

**Comment by jhujasonw** [comment]
Note that the ENV vars will need to be added to the drupal base service and that those variables will need to be properly configured, via secrets probably, for the instances and the local stack.  

There is a divergence with the local stack and cloud instances in that local stack uses MinIO and the cloud stack uses full S3.  Cloud may not need some of those variables, where the local stack may need all or more of them.

**Comment by jhujasonw** [comment]
This is done for the cloud instances and is waiting on https://github.com/jhu-idc/idcApp-k8s/pull/55 to merge to fully close.

**Comment by jhujasonw** [comment]
PR merged, done in local using minio.  Closing issue.
