### ISSUE TITLE
create unique identifier for all items in iDC

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#383]
This ticket is about adding a field (field_unique_id) to all nodes, media and taxonomy terms so they have a unique identifier. 

Field must be: 
 - required
 - single value
 - plain text field ~~50~~ 255 characters max 
 - case insensitive (for example, `uid:1243-BA07` and `UID:1243-ba07` are equivalent strings)

Tasks: 
 - [x] [add field to node content types, their migrations, tests & export (Collection and Repository Item)](https://github.com/jhu-idc/iDC-general/issues/384)
 - [x] [add field to media types, their migrations, and tests](https://github.com/jhu-idc/iDC-general/issues/385)
 - [x] [add field to taxonomy vocabularies , their migrations, and tests](https://github.com/jhu-idc/iDC-general/issues/386)
 - [x] [write constraint(s) for each type (node, media, taxonomy terms) to guarantee uniqueness among the ids](https://github.com/jhu-idc/iDC-general/issues/387)
 - [x] https://github.com/jhu-idc/iDC-general/issues/388
 - [x] https://github.com/jhu-idc/iDC-general/issues/391

Questions
 - do we need this field on system managed taxonomies? Specifically Islandora Display, Islandora Model, Islandora Media use
 -  is the `field_unique_id` hidden from the UI?
 - are we going to enforce them being uuids?

**Comment by birkland** [comment]
My quick reaction to questions:
> do we need this field on system managed taxonomies? Specifically Islandora Display, Islandora Model, Islandora Media use

no

> is the field_iid hidden from the UI?

yes

>are we going to enforce them being uuids?

no

**Comment by bseeger** [comment]
@birkland  does the max of 50 characters seem reasonable? Should it be less? Wasn't sure about that one.

**Comment by birkland** [comment]
I'd go for 255, to wring the most out of the eight bytes we get from VARCHAR(N <= 255)

**Comment by bseeger** [comment]
Note that the length of the field_unique_id ended up being 128, as it's based on what the uuid_item FieldType is. I think we can change it, but not sure and haven't looked through the parent class to see what ripples might happen if we do change it.
